spring.application.name=rcontractual

# ── Servidor ──────────────────────────────────────────────────
server.port=8085
server.servlet.context-path=/rcontractual

# ── Oracle DataSource ─────────────────────────────────────────
spring.datasource.url=jdbc:oracle:thin:@//10.100.100.207:1521/CDBAPPDV_PDB1.snetdesadb01.vcndesa02.oraclevcn.com
spring.datasource.username=contratos
spring.datasource.password=zQFejM$)PWysxaB6j9%f5iK
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ── Connection Pool (HikariCP) ────────────────────────────────
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# ── JPA / Hibernate ───────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=CONTRATOS

# ── Logging ───────────────────────────────────────────────────
logging.level.gov.idiger.rcontractual=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.hibernate.SQL=DEBUG

# Habilitar servicio de recursos estáticos
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**