spring.application.name=rcontractual

# ── Servidor ──────────────────────────────────────────────────
server.port=8085
server.servlet.context-path=/rcontractual

# ── Oracle DataSource ─────────────────────────────────────────
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//xx.xx.xx.xx:xxxx/xxx}
spring.datasource.username=${DB_USERNAME:xx}
spring.datasource.password=${DB_PASSWORD:xx}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ── Connection Pool (HikariCP) ────────────────────────────────
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# ── JPA / Hibernate ───────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=CONTRATOS

# ── Logging ───────────────────────────────────────────────────
logging.level.gov.idiger.rcontractual=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.hibernate.SQL=DEBUG

# Habilitar servicio de recursos estáticos
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# Google reCAPTCHA v2
recaptcha.site-key=${RECAPTCHA_SITE_KEY:xx}
recaptcha.secret-key=${RECAPTCHA_SECRET_KEY:xx}
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify


# CONFIGURACION DE CORREO
app.mail.enabled=true
app.mail.from=${MAIL_FROM:no-reply@example.com}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:xx}
spring.mail.password=${MAIL_PASSWORD:xx}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
